using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace NeoIni.Generators
{
    [Generator]
    public sealed class NeoIniMappingGenerator : IIncrementalGenerator
    {
        private sealed class PropertyMeta(string containingTypeName, string propertyName, string propertyTypeName,
                string section, string key, string? defaultValueLiteral)
        {
            public string ContainingTypeName { get; private set; } = containingTypeName;
            public string PropertyName { get; private set; } = propertyName;
            public string PropertyTypeName { get; private set; } = propertyTypeName;
            public string Section { get; private set; } = section;
            public string Key { get; private set; } = key;
            public string? DefaultValueLiteral { get; private set; } = defaultValueLiteral;
        }

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var propertyDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => IsCandidateProperty(node),
                    transform: static (ctx, _) => GetPropertyInfo(ctx))
                .Where(static info => info is not null)!;
            var groupedByType = propertyDeclarations
                .Collect()
                .Select(static (props, _) =>
                {
                    Dictionary<string, List<PropertyMeta>> dict = [];
                    foreach (var p in props)
                    {
                        if (p is null) continue;
                        if (!dict.TryGetValue(p.ContainingTypeName, out var list))
                        {
                            list = [];
                            dict[p.ContainingTypeName] = list;
                        }
                        list.Add(p);
                    }
                    return dict;
                });
            context.RegisterSourceOutput(groupedByType, static (spc, grouped) =>
            {
                if (grouped.Count == 0) return;
                GenerateExtensions(spc, grouped);
            });
        }

        private static void GenerateExtensions(SourceProductionContext context, Dictionary<string, List<PropertyMeta>> grouped)
        {
            StringBuilder sb = new();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.AppendLine("namespace NeoIni");
            sb.AppendLine("{");
            sb.AppendLine("    public static class NeoIniDocumentExtensions");
            sb.AppendLine("    {");
            sb.AppendLine("        public static T Get<T>(this NeoIniDocument document) where T : new()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (document is null) throw new ArgumentNullException(nameof(document));");
            sb.AppendLine("            Type t = typeof(T);");
            sb.AppendLine();
            foreach (var kvp in grouped)
            {
                string typeName = kvp.Key;
                sb.AppendLine($"            if (t == typeof({typeName}))");
                sb.AppendLine("            {");
                sb.AppendLine($"                var cfg = new {typeName}();");
                foreach (var p in kvp.Value)
                {
                    var sectionLit = EscapeStringLiteral(p.Section);
                    var keyLit = EscapeStringLiteral(p.Key);
                    string defaultValue = p.DefaultValueLiteral ?? GetDefaultLiteralForType(p.PropertyTypeName);
                    sb.AppendLine($"                cfg.{p.PropertyName} = document.GetValue<{p.PropertyTypeName}>({sectionLit}, {keyLit}, {defaultValue});");
                }
                sb.AppendLine("                return (T)(object)cfg;");
                sb.AppendLine("            }");
            }
            sb.AppendLine("            return new T();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static void Set<T>(this NeoIniDocument document, T config)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (document is null) throw new ArgumentNullException(nameof(document));");
            sb.AppendLine("            if (config is null) throw new ArgumentNullException(nameof(config));");
            sb.AppendLine("            Type t = typeof(T);");
            sb.AppendLine();
            foreach (var kvp in grouped)
            {
                string typeName = kvp.Key;
                sb.AppendLine($"            if (t == typeof({typeName}))");
                sb.AppendLine("            {");
                sb.AppendLine($"                var cfg = ({typeName})(object)config;");
                foreach (var p in kvp.Value)
                {
                    var sectionLit = EscapeStringLiteral(p.Section);
                    var keyLit = EscapeStringLiteral(p.Key);
                    sb.AppendLine($"                document.SetValue({sectionLit}, {keyLit}, cfg.{p.PropertyName});");
                }
                sb.AppendLine("                return;");
                sb.AppendLine("            }");
            }
            sb.AppendLine("            throw new NotSupportedException($\"Type {t.FullName} is not registered in NeoIni source generator.\");");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            context.AddSource("NeoIniDocumentExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static string EscapeStringLiteral(string? value)
        {
            if (value is null) return "null";
            return "@\"" + value.Replace("\"", "\"\"") + "\"";
        }

        private static string GetDefaultLiteralForType(string fullyQualifiedTypeName) => "default(" + fullyQualifiedTypeName + ")";

        private static bool IsCandidateProperty(SyntaxNode node) => node is PropertyDeclarationSyntax { AttributeLists.Count: > 0 };

        private static PropertyMeta? GetPropertyInfo(GeneratorSyntaxContext context)
        {
            if (context.Node is not PropertyDeclarationSyntax propertySyntax) return null;
            var model = context.SemanticModel;
            if (model.GetDeclaredSymbol(propertySyntax) is not IPropertySymbol propertySymbol) return null;
            var attr = propertySymbol.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass is not null && a.AttributeClass.ToDisplayString() == "NeoIni.Annotations.NeoIniKeyAttribute");
            if (attr is null) return null;
            string section = "";
            string key = "";
            string? defaultValueLiteral = null;
            if (attr.ConstructorArguments.Length >= 2)
            {
                section = (string?)attr.ConstructorArguments[0].Value ?? "";
                key = (string?)attr.ConstructorArguments[1].Value ?? "";
            }
            if (attr.ConstructorArguments.Length >= 3)
            {
                var dvConstant = attr.ConstructorArguments[2];
                if (dvConstant.Value is not null)
                {
                    object dv = dvConstant.Value;
                    if (dv is string s) defaultValueLiteral = EscapeStringLiteral(s);
                    else if (dv is bool b) defaultValueLiteral = b ? "true" : "false";
                    else if (dv is char c) defaultValueLiteral = "'" + c.ToString().Replace("'", "\\'") + "'";
                    else if (dv is IFormattable f) defaultValueLiteral = f.ToString(null, CultureInfo.InvariantCulture);
                    else defaultValueLiteral = dv.ToString();
                }
            }
            var containingType = propertySymbol.ContainingType;
            string typeName = containingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string propTypeName = propertySymbol.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return new(typeName, propertySymbol.Name, propTypeName, section, key, defaultValueLiteral);
        }
    }
}
